# Generated by Django 3.0.2 on 2020-01-06 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50)),
                ('day', models.DecimalField(decimal_places=0, default=0, max_digits=3)),
                ('month', models.CharField(max_length=5)),
                ('year', models.DecimalField(decimal_places=0, default=0, max_digits=4)),
                ('hour', models.DecimalField(decimal_places=0, default=0, max_digits=2)),
                ('minute', models.DecimalField(decimal_places=0, default=0, max_digits=2)),
                ('second', models.DecimalField(decimal_places=0, default=0, max_digits=2)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
    ]
